### ISSUE TITLE
Unit testing 

### ISSUE THREAD

**Issue by Abiramikoperundevi** [Karthikeyan1411/M1_Game_Quiz#1]
I need help related to unit testing how did u got this unit tesing badge please help me to do

**Comment by Karthikeyan1411** [comment]
Message me in
Whatsapp: 7092981728

**Comment by Karthikeyan1411** [comment]
msg me in
Whatspp: 7092981728

**Comment by Karthikeyan1411** [comment]
In actions tab, u will create workflow for badges
